### ISSUE TITLE
构建项目失败

### ISSUE THREAD

**Issue by Danjuanlab** [axiuya/electron-bluetooth#1]
yarn install构建项目失败，请问是否有什么前置的依赖需要安装？从代码提示上看似乎是需要windows build tool，但是我看依赖中并没有使用noble库。

`PS C:\Users\DJlab_Effect\Desktop\electron-bluetooth-main> yarn install
yarn install v1.22.10
warning ..\..\package.json: No license field
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
warning electron-rebuild > lzma-native > node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
warning electron-rebuild > node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning electron-rebuild > node-gyp > request > har-validator@5.1.5: this library is no longer supported
warning electron-rebuild > node-gyp > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/6] ⢀ drivelist
[2/6] ⢀ @serialport/bindings
[-/6] ⢀ waiting...
[6/6] ⢀ electron
error C:\Users\DJlab_Effect\Desktop\electron-bluetooth-main\node_modules\drivelist: Command failed.
Exit code: 1
Command: prebuild-install || node-gyp rebuild
Arguments: 
Directory: C:\Users\DJlab_Effect\Desktop\electron-bluetooth-main\node_modules\drivelist
Output:
prebuild-install WARN install No prebuilt binaries found (target=14.17.1 runtime=node arch=x64 libc= platform=win32)

C:\Users\DJlab_Effect\Desktop\electron-bluetooth-main\node_modules\drivelist>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild ) 
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@14.17.1 | win32 | x64
gyp info find Python using Python version 3.6.8 found at "C:\Programs\Python\Python36\python.exe"
gyp info find VS using VS2017 (15.9.28307.1274) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Programs\Python\Python36\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\DJlab_Effect\\Desktop\\electron-bluetooth-main\\node_modules\\drivelist\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\DJlab_Effect\\AppData\\Local\\node-gyp\\Cache\\14.17.1\\include\\node\\common.gypi',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\DJlab_Effect\\AppData\\Local\\node-gyp\\Cache\\14.17.1',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\DJlab_Effect\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\14.17.1\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\DJlab_Effect\\Desktop\\electron-bluetooth-main\\node_modules\\drivelist',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\DJlab_Effect\\Desktop\\electron-bluetooth-main\\node_modules\\drivelist\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
�ڴ˽��������һ������һ����Ŀ����Ҫ���ò������ɣ������ӡ�/m�����ء�
  drivelist.cpp
  device-descriptor.cpp
  list.cpp
  win_delay_load_hook.cc
c:\users\djlab_effect\appdata\local\node-gyp\cache\14.17.1\include\node\node.h(67): fatal error C1083: �޷��򿪰����ļ�: ��v8.h��: No such file or directory (����Դ�ļ� ..\src\drivelist.cpp) [C:\Users\DJlab _Effect\Desktop\electron-bluetooth-main\node_modules\drivelist\build\drivelist.vcxproj]
c:\users\djlab_effect\appdata\local\node-gyp\cache\14.17.1\include\node\node.h(67): fatal error C1083: �޷��򿪰����ļ�: ��v8.h��: No such file or directory (����Դ�ļ� ..\src\device-descriptor.cpp) [C:\Use rs\DJlab_Effect\Desktop\electron-bluetooth-main\node_modules\drivelist\build\drivelist.vcxproj]  
c:\users\djlab_effect\appdata\local\node-gyp\cache\14.17.1\include\node\node.h(67): fatal error C1083: �޷��򿪰����ļ�: ��v8.h��: No such file or directory (����Դ�ļ� ..\src\windows\list.cpp) [C:\Users\DJ lab_Effect\Desktop\electron-bluetooth-main\node_modules\drivelist\build\drivelist.vcxproj]       
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:375:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\DJlab_Effect\Desktop\electron-bluetooth-main\node_modules\drivelist`

**Comment by axiuya** [comment]
@Danjuanlab 不需要任何依赖，这是js api中自带的，而且只能是BLE 4.0及其以上版本的设备，这个代码我把串口通讯的demo也放了进去，所以你可以把 "drivelist"、“serialport“、”usb“、”node-abi“几个依赖删掉

**Comment by Danjuanlab** [comment]
@axiuya 感谢，删除你说的部分依赖后，已经可以正常工作。刚也看了下，你用的是web-bluetooth api，这种方案由于安全因素需要需要手动扫描连接，不适合我呢。也是苦于windows 10平台下nodejs 和python都没有什么正常的ble方案，哎看来是要放弃BLE了。感谢你~
